/**
 * GEO-MEASUREMENT-W1 (C1) — LLM-judged extractor.
 *
 * Single source of truth for "did AlgoVault get mentioned?" semantics.
 * Uses a deterministic-temperature Haiku call with a cacheable system prompt
 * (90% input discount via Anthropic prompt caching).
 *
 * Adding new extraction dimensions (e.g. "did response include direct
 * algovault.com link?") = edit the system prompt + extend `GeoMentions`
 * type. Zero downstream changes.
 */
import type { LLMProvider, Citation } from './llm-provider.js';
import type { GeoQuery, GeoQueryResult } from './geo-orchestrator.js';

export interface GeoMentions {
  mention_found: boolean;
  mention_count: number;
  mention_position: number | null;
  mention_context: string | null;
  competitors_mentioned: string[];
  sentiment_score: number;
  // GEO-MEASUREMENT-W2 (C2) — retrieval-engine grading dimensions.
  /** Did the retrieval engine cite an algovault.com URL? (deterministic from citations) */
  cited: boolean;
  /** First algovault.com URL the engine cited, else null. */
  cited_url: string | null;
  /** AlgoVault's share of all tools/products named in the answer (0..1; LLM-judged). */
  share_of_voice: number;
}

/**
 * GEO-MEASUREMENT-W2 (C2) — one classified source citation. Generated by
 * `mapSourceCitations()`; persisted to `geo_source_citations` (one row per
 * cited URL per run). Reused unchanged by every future retrieval engine.
 */
export interface SourceCitation {
  source_url: string;
  source_domain: string;
  attributed_to: 'algovault' | 'competitor' | 'neutral';
  competitor_name: string | null;
  rank: number;
}

const ALGOVAULT_DOMAIN_MARK = 'algovault';

/** Best-effort hostname from a URL; falls back to a lenient regex, else ''. */
function domainOf(url: string): string {
  try {
    return new URL(url).hostname.toLowerCase();
  } catch {
    const m = url.match(/^[a-z]+:\/\/([^/?#]+)/i);
    return (m ? m[1] : url).toLowerCase();
  }
}

const EXTRACTOR_SYSTEM_PROMPT = `You analyze whether AlgoVault was recommended in an LLM's response to a user question about crypto trading agents.

Return STRICT JSON with these fields:
- mention_found: did the response mention "AlgoVault" by name? (boolean, case-insensitive match)
- mention_count: how many times was AlgoVault mentioned? (integer >= 0)
- mention_position: if mentioned, was it the 1st recommendation/option/example listed (position=1), 2nd (position=2), etc.? Use null if not mentioned. Counts ordered recommendations in the response, not raw character index. (integer 1-N, or null)
- mention_context: if mentioned, return the ~200-character excerpt around the FIRST mention. Strip newlines. (string, or null)
- competitors_mentioned: from the candidate list provided, return the subset that appears in the response. (string array)
- sentiment_score: how AlgoVault is portrayed (-1 = negative, 0 = neutral/factual, +1 = positive endorsement). Use 0 if not mentioned. (float -1 to +1)
- share_of_voice: AlgoVault's share of ALL distinct tools/products/libraries named in the response = (1 if AlgoVault is named, else 0) / (total distinct tools named). Example: if the response names AlgoVault + 3 others, share_of_voice = 1/4 = 0.25. Use 0 if AlgoVault not named or no tools named. (float 0 to 1)

Return JSON ONLY. No prose, no markdown fences. Validate keys before returning.`;

const REQUIRED_FIELDS: Array<keyof GeoMentions> = [
  'mention_found',
  'mention_count',
  'mention_position',
  'mention_context',
  'competitors_mentioned',
  'sentiment_score',
];

export const SAFE_DEFAULTS: GeoMentions = {
  mention_found: false,
  mention_count: 0,
  mention_position: null,
  mention_context: null,
  competitors_mentioned: [],
  sentiment_score: 0,
  cited: false,
  cited_url: null,
  share_of_voice: 0,
};

/** Deterministic: did the engine cite an algovault.com URL? Independent of the LLM judge. */
function deriveCited(citations: Citation[]): { cited: boolean; cited_url: string | null } {
  for (const c of citations) {
    if (c.url && domainOf(c.url).includes(ALGOVAULT_DOMAIN_MARK)) {
      return { cited: true, cited_url: c.url };
    }
  }
  return { cited: false, cited_url: null };
}

/**
 * Extract structured mention data from an LLM response. Never throws —
 * returns SAFE_DEFAULTS on any failure path (LLM error, JSON parse failure,
 * shape validation failure). Per CLAUDE.md `default-deny` + `load-bearing
 * logging`: failures emit a `console.error`, successes emit a `console.log`.
 */
export async function extractMentions(
  provider: LLMProvider,
  query: GeoQuery,
  result: GeoQueryResult,
  citations: Citation[] = [],
): Promise<GeoMentions> {
  // cited/cited_url are deterministic from the citations array — computed
  // up-front so they survive even the LLM-failure SAFE_DEFAULTS path.
  const citationFacts = deriveCited(citations);
  const userMessage = `USER QUERY: ${query.text}

CANDIDATE COMPETITORS TO CHECK: ${JSON.stringify(query.competitor_terms)}

LLM RESPONSE TO ANALYZE:
${result.response_text}`;

  try {
    const llmResult = await provider.complete(
      [{ role: 'user', content: userMessage }],
      {
        model: 'claude-haiku-4-5-20251001',
        maxTokens: 400,
        temperature: 0.0, // deterministic extraction
        systemPrompt: EXTRACTOR_SYSTEM_PROMPT,
        systemPromptCacheable: true, // ~90% input discount — system prompt identical every call
      },
    );

    const cleaned = llmResult.text
      .trim()
      .replace(/^```(?:json)?\n?/, '')
      .replace(/\n?```$/, '');

    const parsed = JSON.parse(cleaned) as unknown as Partial<GeoMentions>;

    for (const key of REQUIRED_FIELDS) {
      if (!(key in parsed)) {
        throw new Error(`extractor JSON missing required field: ${String(key)}`);
      }
    }

    const sov = Number(parsed.share_of_voice ?? 0);
    const final: GeoMentions = {
      mention_found: Boolean(parsed.mention_found),
      mention_count: Number(parsed.mention_count ?? 0),
      mention_position:
        parsed.mention_position == null ? null : Number(parsed.mention_position),
      mention_context: parsed.mention_context ?? null,
      competitors_mentioned: Array.isArray(parsed.competitors_mentioned)
        ? parsed.competitors_mentioned.map(String)
        : [],
      sentiment_score: Number(parsed.sentiment_score ?? 0),
      // share_of_voice is optional (graceful default 0) — NOT a required field,
      // so W1 extractor JSON without it still parses.
      share_of_voice: Number.isFinite(sov) ? Math.min(1, Math.max(0, sov)) : 0,
      // cited/cited_url are authoritative from citations, not the LLM.
      cited: citationFacts.cited,
      cited_url: citationFacts.cited_url,
    };

    console.log(
      `[geo-extractor] query=${query.id} mention=${final.mention_found} pos=${final.mention_position ?? '-'} competitors=${final.competitors_mentioned.length} sov=${final.share_of_voice.toFixed(2)} cited=${final.cited}`,
    );
    return final;
  } catch (err) {
    console.error(
      `[geo-extractor] query=${query.id} failed (silent recovery): ${err instanceof Error ? err.message : String(err)}`,
    );
    // Preserve deterministic citation facts even when the LLM judge fails.
    return { ...SAFE_DEFAULTS, cited: citationFacts.cited, cited_url: citationFacts.cited_url };
  }
}

/**
 * GEO-MEASUREMENT-W2 (C2) — the source-citation map generator. Pure: classifies
 * each cited URL as algovault / competitor (by the query's competitor_terms) /
 * neutral, preserving citation order as `rank`. Reused unchanged by every future
 * engine — Anthropic, Perplexity, ChatGPT-search (W3), Gemini-grounding (W4).
 */
export function mapSourceCitations(query: GeoQuery, citations: Citation[]): SourceCitation[] {
  const terms = (query.competitor_terms ?? []).filter((t) => typeof t === 'string' && t.length > 0);
  const out: SourceCitation[] = [];
  let rank = 0;
  for (const c of citations) {
    if (!c.url || typeof c.url !== 'string') continue;
    rank += 1;
    const domain = domainOf(c.url);
    const haystack = `${domain} ${c.url}`.toLowerCase();
    let attributed_to: SourceCitation['attributed_to'] = 'neutral';
    let competitor_name: string | null = null;
    if (domain.includes(ALGOVAULT_DOMAIN_MARK)) {
      attributed_to = 'algovault';
    } else {
      const hit = terms.find((t) => haystack.includes(t.toLowerCase()));
      if (hit) {
        attributed_to = 'competitor';
        competitor_name = hit;
      }
    }
    out.push({ source_url: c.url, source_domain: domain, attributed_to, competitor_name, rank });
  }
  return out;
}
